# Generated by Django 6.1.2 on 2026-10-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("language", models.CharField(default="en-US", max_length=20)),
                ("genre", models.CharField(default="pop", max_length=60)),
                ("mood", models.CharField(default="uplifting", max_length=60)),
                ("vocal", models.CharField(default="female", max_length=20)),
                ("tempo", models.PositiveIntegerField(default=96)),
                ("key", models.CharField(default="C", max_length=10)),
                ("lyrics", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
